SELECT C.CAR_ID
     , C.CAR_TYPE
     , FLOOR(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) AS FEE
  FROM CAR_RENTAL_COMPANY_CAR C
INNER JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
        ON C.CAR_TYPE = P.CAR_TYPE
       AND P.DURATION_TYPE = '30일 이상'
 WHERE P.CAR_TYPE IN ('세단', 'SUV')
   AND FLOOR(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) >= 500000
   AND FLOOR(C.DAILY_FEE * 30 * (100 - P.DISCOUNT_RATE) / 100) < 2000000
   AND C.CAR_ID NOT IN (SELECT CAR_ID
                       FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
                      WHERE START_DATE <= DATE '2022-11-30'
                        AND END_DATE >= DATE '2022-11-01'
                    )
ORDER BY FEE DESC
       , CAR_TYPE
       , CAR_ID DESC
