-- 코드를 입력하세요
SELECT EXTRACT(YEAR FROM SALES_DATE) AS YEAR
     , EXTRACT(MONTH FROM SALES_DATE) AS MONTH
     , COUNT(DISTINCT U.USER_ID) AS PURCHASED_USERS
     , ROUND(
        COUNT(DISTINCT O.USER_ID) / (
            SELECT COUNT(*)
            FROM USER_INFO
            WHERE EXTRACT(YEAR FROM JOINED) = 2021
        ),
        1
     ) AS PUCHASED_RATIO
FROM USER_INFO U
INNER JOIN ONLINE_SALE O
ON U.USER_ID = O.USER_ID
WHERE EXTRACT(YEAR FROM U.JOINED) = 2021
GROUP BY EXTRACT(YEAR FROM SALES_DATE)
       , EXTRACT(MONTH FROM SALES_DATE)
ORDER BY EXTRACT(YEAR FROM SALES_DATE) ASC
       , EXTRACT(MONTH FROM SALES_DATE) ASC