-- 코드를 작성해주세요
# SELECT ITEM_ID
#      , ITEM_NAME
#      , RARITY
#      FROM ITEM_INFO  
#  WHERE ITEM_ID IN (SELECT ITEM_ID
#           FROM ITEM_TREE 
#          WHERE PARENT_ITEM_ID IS NOT NULL)
#  ORDER BY ITEM_ID DESC
SELECT C.ITEM_ID
     , C.ITEM_NAME
     , C.RARITY
  FROM ITEM_INFO C 
  JOIN ITEM_TREE T
    ON C.ITEM_ID = T.ITEM_ID
  JOIN ITEM_INFO P
    ON T.PARENT_ITEM_ID = P.ITEM_ID
 WHERE P.RARITY = 'RARE'
 ORDER BY C.ITEM_ID DESC;